#!/bin/bash
set -e

rm -f server

as -o server.o main.s
ld -s -n --no-warn-rwx-segments -z noexecstack -o server server.o

# Strip leftover metadata and GNU note sections
objcopy -R .note.gnu.build-id -R .note.gnu.property -R .comment server
rm server.o
